CREATE DATABASE CLOUD9DETAILS;

USE CLOUD9DETAILS;

CREATE TABLE CLOUD(

	 EMP_ID INT PRIMARY KEY,
     EMP_NAME VARCHAR (45),
     JOB_DESC VARCHAR (25),
     SALARY INT 
);

INSERT  INTO CLOUD VALUES (1,"YUVARAJ","TDL",12500),
(2,"DIVYA","FRONT END",8500),
(3,"DINESH","TDL",8500),
(4,"KOMATHI","TDL",8000),
(5,"KAVIYA","TDL",7800),
(6,"VIJAY","TDL",5000),
(7,"MONITHA","FRONT END",5000),
(8,"PRIYADHARSHINI","DIGITAL MARKETING",4500),
(9,"BHARATH","FRONT END",5000);

SELECT * FROM CLOUD;

-- WHERE CLASS 

SELECT * FROM CLOUD 
WHERE  EMP_NAME  = "DIVYA";

SELECT * FROM CLOUD 
WHERE SALARY<5000;

SELECT * FROM CLOUD 
WHERE  SALARY>6000;

SELECT * FROM CLOUD 
WHERE  SALARY=5000 AND JOB_DESC = "FRONT END";

SELECT * FROM CLOUD 
WHERE SALARY BETWEEN 5000 AND 12000 AND JOB_DESC="TDL";

SELECT * FROM CLOUD 
LIMIT 3;

-- LIKE 

SELECT * FROM CLOUD 
WHERE EMP_NAME LIKE 'D%';

-- DISTINCT 

SELECT DISTINCT  JOB_DESC FROM CLOUD ;

-- ORDER BY 

SELECT * FROM CLOUD 
ORDER BY SALARY ;

SELECT * FROM CLOUD 
ORDER BY SALARY DESC;

SELECT * FROM CLOUD 
ORDER BY SALARY ASC;

SELECT * FROM CLOUD 
WHERE JOB_DESC = "TDL"
ORDER BY SALARY ASC;

SELECT * FROM CLOUD 
ORDER BY JOB_DESC,EMP_NAME;

-- FUNCTIONS (COUNT,AVG,SUM,MIN,MAX)

SELECT COUNT(*) FROM CLOUD;

SELECT COUNT(JOB_DESC)TOTAL_JOBS FROM CLOUD;

SELECT SUM(SALARY) FROM CLOUD 
WHERE JOB_DESC = "FRONT END";

SELECT AVG(SALARY) FROM CLOUD 
WHERE JOB_DESC="DIGITAL MARKETING";

SELECT MAX(SALARY) FROM CLOUD;

SELECT MIN(SALARY) FROM CLOUD;

-- STRING (UCASE,CHARLENGTH,CONCAT,FORMAT,LEF)

SELECT UCASE(EMP_NAME)NAME,SALARY FROM CLOUD;

SELECT EMP_NAME,CHAR_LENGTH(EMP_NAME)CHA FROM CLOUD;

SELECT EMP_NAME,CONCAT("RS.",SALARY)SALARY  FROM CLOUD;

SELECT EMP_NAME,CONCAT("RS.",FORMAT(SALARY,0)) FROM CLOUD;

SELECT EMP_NAME,LEFT(JOB_DESC,2) FROM CLOUD;

-- GROUPBY AND HAVING 

SELECT JOB_DESC,FORMAT(AVG(SALARY),0)AVG_SAL FROM CLOUD
GROUP BY JOB_DESC;

SELECT JOB_DESC,COUNT(EMP_ID) FROM CLOUD 
GROUP BY JOB_DESC;