USE CLOUD9DETAILS;

CREATE TABLE BRANCH(

	BRANCH_ID INT PRIMARY KEY,
    BRANCH_NAME VARCHAR(45),
    BRANCH_ADDRESS VARCHAR(200)
);

INSERT INTO BRANCH VALUES (1,"HEAD OFFICE-CHENNAI","NO-16 VOC STREET ANNANAGAR CHENNAI"),
(2,"KOVAI","NO 15/52 PILLAIYARKOVIL STREET GANDHIPURAM COIMBATORE"),
(3,"VELLORE","NO 121 SANNATHI STREET NEAR PVR VELOCITY SILK MILL VELLORE");

CREATE TABLE EMPLOYEEE(

	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(30),
    JOB_DESC VARCHAR(40),
    SALARY INT ,
    BRANCH_ID INT,
    CONSTRAINT FK_BRANCH_ID FOREIGN KEY(BRANCH_ID) REFERENCES  BRANCH(BRANCH_ID)
);

INSERT INTO EMPLOYEEE VALUES (1,"YUVARAJ","TDL",12500,3), 
(2,"DIVYA","FRONT END",8500,1),
(3,"DINESH","TDL",8500,1),
(4,"KOMATHI","TDL",8000,3),
(5,"KAVIYA","TDL",7800,2),
(6,"VIJAY","TDL",5000,2),
(7,"MONITHA","FRONT END",5000,3),
(8,"PRIYADHARSHINI","DIGITAL MARKETING",4500,3),
(9,"BHARATH","FRONT END",5000,2),
(10,"RAJU","HR",29999,1);

SELECT * FROM BRANCH;
SELECT * FROM EMPLOYEEE;

-- JOINS -- INNNER JOINS MATCH ONLY MATCHING ROWS 

SELECT EMPLOYEEE.EMP_ID,EMPLOYEEE.EMP_NAME,EMPLOYEEE.JOB_DESC,BRANCH.BRANCH_NAME FROM EMPLOYEEE INNER JOIN BRANCH ON 
EMPLOYEEE.BRANCH_ID =BRANCH.BRANCH_ID
ORDER BY EMP_ID; 

-- RIGHT JOIN 

SELECT EMPLOYEEE.EMP_ID,EMPLOYEEE.EMP_NAME,EMPLOYEEE.JOB_DESC,BRANCH.BRANCH_NAME FROM EMPLOYEEE RIGHT JOIN BRANCH ON 
EMPLOYEEE.BRANCH_ID =BRANCH.BRANCH_ID
ORDER BY EMPLOYEEE.EMP_ID; 